import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  imports: [CommonModule],
  templateUrl: './header.html',
  styleUrl: './header.css',
})
export class Header {
languages=[
  'English',
  'Hindi',
  'Spanish',
  'French',
  'Chinese (Mandarin)',
  'Arabic',
  'Portuguese',
  'Russian',
  'Bengali',
  'Urdu',
  'Japanese',
  'German',
  'Korean',
  'Italian',
  'Turkish',
  'Vietnamese',
  'Persian (Farsi)',
  'Polish',
  'Dutch',
  'Thai',
  'Malay',
  'Indonesian',
  'Greek',
  'Hebrew',
  'Swedish',
  'Finnish',
  'Norwegian',
  'Danish',
  'Czech',
  'Hungarian',
  'Romanian',
  'Serbian',
  'Croatian',
  'Ukrainian',
  'Tamil',
  'Telugu',
  'Gujarati',
  'Marathi',
  'Punjabi',
  'Kannada',
  'Malayalam',
  'Swahili',
  'Tagalog (Filipino)',
  'Burmese',
  'Nepali',
  'Sinhala',
  'Afrikaans',
  'Amharic',
  'Mongolian',
  'Lao',
  'Khmer',
  'Hausa',
  'Yoruba',
  'Zulu'
]
}
